import mongoose from "mongoose";

const TeamMemberSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    role: {
      type: String,
      enum: [
        "Project Manager",
        "Scrum Master",
        "Product Owner",
        "Program Manager",
        "Delivery Lead",
        "Developer",
        "Frontend Developer",
        "Backend Developer",
        "Full-Stack Developer",
        "Mobile Developer",
        "DevOps Engineer",
        "Site Reliability Engineer (SRE)",
        "Data Engineer",
        "Machine Learning Engineer",
        "Designer",
        "UI/UX Designer",
        "Graphic Designer",
        "Motion Designer",
        "Product Designer",
        "QA Engineer",
        "Tester",
        "Automation Tester",
        "Performance Tester",
        "Security Tester",
        "Business Analyst",
        "Operations Manager",
        "Customer Success Manager",
        "Support Specialist",
        "Account Manager",
        "Marketing Manager",
        "Content Marketer",
        "Growth Hacker",
        "Sales Representative",
        "HR Coordinator",
        "Recruiter",
        "Talent Acquisition Specialist",
        "Finance Analyst",
        "Compliance Officer",
        "Legal Counsel",
        "Content Writer",
        "Copywriter",
        "Editor",
        "Video Producer",
        "Photographer",
        "Client",
        "Sponsor",
        "Vendor",
        "Consultant",
        "Advisor",
        "Member",
        "Other",
      ],
      default: "Member",
    },
    status: {
      type: String,
      enum: ["Active", "Inactive"],
      default: "Active",
    },
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Project",
    },
    addedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  { timestamps: true }
);

export default mongoose.models.TeamMember ||
  mongoose.model("TeamMember", TeamMemberSchema);
